server:
  port: 7071

spring:
  application:
    name: service-provider # 应用名称（集群下相同）

# 配置Eureka Server注册中心
eureka:
  instance:
    hostname: eureka-${server.port} # 主机名，不配置的时候将根据操作系统的主机名来获取
    prefer-ip-address: true # 是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    #    register-with-eureka: false # 是否将自己注册到注册中心，默认为true
    #    fetch-registry: false # 是否从注册中心获取服务注册信息，默认为true
    service-url:          # 注册中心对外暴露的注册地址
      dafaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka

# 度量指标监控与健康检查
management:
  endpoints:
    web:
      exposure:
        include: shutdown # 开启shutdown端点访问
  endpoint:
    shutdown:
      enabled: true # 开启shutdown实现优雅停服