server:
  port: 9090

spring:
  application:
    name: service-consumer # 应用名称（集群下相同）

# 配置Eureka Server注册中心
#eureka:
#  client:
#    register-with-eureka: false # 是否将自己注册到注册中心，默认为true
#    registry-fetch-interval-seconds: 10 # 表示Eureka Client间隔多久去服务器拉取注册信息，默认为30秒
#    #    fetch-registry: false # 是否从注册中心获取服务注册信息，默认为true
#    service-url:          # 注册中心对外暴露的注册地址
#      dafaultZone: http://localhost:8761/eureka, http://localhost:8762/eureka

# 负载均衡策略（局部配置）
service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    # 指定具体的Provider服务列表，多个用逗号隔开
    listOfServers: http://localhost:7070,http://localhost:7071

